import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  {
    ignores: [
      'node_modules/**',
      // Every build output directory. `npm run verify` uses .next-verify and
      // the Playwright harness uses .next-e2e so neither clobbers a running
      // dev server — all of them are generated, none of them is source.
      '.next*/**',
      'test-results/**',
      'playwright-report/**',
      '.vercel/**',
      'out/**',
      'build/**',
      // Agent tooling and scratch space. Vendored scripts with their own
      // conventions; linting them only produces noise in CI.
      '.claude/**',
      '.agents/**',
      'scratch/**',
      'reference/**',
      'design-system/**',
      'next-env.d.ts',
      // Generated by `npm run images` — edited by the script, not by hand.
      'src/content/media/generated.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Content governance (spec §36): no unreviewed placeholder text can ship
      // silently. TODO/FIXME must be visible in CI output.
      'no-warning-comments': ['warn', { terms: ['todo', 'fixme'], location: 'start' }],
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
    },
  },
];

export default eslintConfig;
