// GENERATED by scripts/build-images.mjs — do not edit by hand.
// Run `npm run images` after changing scripts/image-manifest.mjs.
import type { ImageRef } from '@/lib/content/schema';

export type MediaId = 'hero-office' | 'about-desk' | 'cover-school-education' | 'cover-tamil-development' | 'cover-information-publicity' | 'cover-egmore' | 'edu-classroom-students' | 'edu-primary-classroom' | 'edu-kit-distribution' | 'edu-certificates' | 'edu-infrastructure' | 'edu-foundation-stone' | 'edu-smart-classroom' | 'edu-department-office' | 'td-excavation-aerial' | 'td-excavation-site' | 'td-rock-shelter' | 'td-inscriptions' | 'td-museum-artefact' | 'td-cultural-programme' | 'td-awards' | 'td-heritage-walk' | 'dipr-press-microphones' | 'dipr-press-scrum' | 'dipr-photo-archive' | 'dipr-archival-display' | 'dipr-book-exhibition' | 'dipr-book-stall' | 'dipr-press-conference' | 'dipr-media-gathering' | 'egmore-site-review' | 'egmore-public-facility' | 'egmore-petitions' | 'egmore-doorstep' | 'egmore-community-meal' | 'egmore-inauguration' | 'egmore-street-meeting' | 'egmore-public-gathering';

export const MEDIA: Readonly<Record<MediaId, ImageRef>> = {
  'hero-office': {
    src: '/images/hero/office.webp',
    width: 1800,
    height: 2250,
    alt: {
      en: "Rajmohan Arumugam at his desk in the ministerial office, with departmental files and a bookshelf behind him.",
      ta: "அமைச்சர் அலுவலகத்தில் தமது மேசையில் ராஜ்மோகன் ஆறுமுகம் — துறை ஆவணங்களும், பின்னால் நூல் அலமாரியும்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMAA8ABIByJbACdAEOeXJGOsOAAMyYhBT7R1BUqQsse4TtajZyKuCk8Inm5rI5o+XGqSIoYcRSXwfOTWDbpUCtipcdID0NRuiHHGHZAAA=',
  },
  'about-desk': {
    src: '/images/about/desk.webp',
    width: 1600,
    height: 1067,
    alt: {
      en: "Rajmohan Arumugam signing departmental files at his desk while an official waits.",
      ta: "அலுவலர் ஒருவர் அருகில் நிற்க, தமது மேசையில் துறை ஆவணங்களில் கையொப்பமிடும் ராஜ்மோகன் ஆறுமுகம்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoMAAgABIByJZACdADbqxfVcQAA/tICtYaASqbCPYhhzYZs3eTXxgC9pPKEnLmwsJMqrfFzSix6WpIuShHVxgRTNeN614AA',
  },
  'cover-school-education': {
    src: '/images/portals/school-education-cover.webp',
    width: 1800,
    height: 1013,
    alt: {
      en: "A school library, with students and staff at the shelves during a departmental visit.",
      ta: "துறை ஆய்வின்போது நூல் அலமாரிகளின் அருகில் மாணவர்களும் பணியாளர்களும் — ஒரு பள்ளி நூலகம்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoMAAcABIByJZACdAYt9dBJn9Rw1AD8j7WUejOHOzJHxsTML5YRK7zMiGsJl5EAp6JMJVJ2KedY5yJshqpk5qabIHqbuj+kgAA=',
  },
  'cover-tamil-development': {
    src: '/images/portals/tamil-development-cover.webp',
    width: 1800,
    height: 1013,
    alt: {
      en: "Bronze and stone sculptures on display in a museum gallery during a Tamil Development visit.",
      ta: "தமிழ் வளர்ச்சித் துறை ஆய்வின்போது அருங்காட்சியகக் கூடத்தில் காட்சிக்கு வைக்கப்பட்டுள்ள வெண்கல, கல் சிற்பங்கள்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoMAAcABIByJbACdADbaRJBAAD+8fgYSJi5xJIPd/DVTiOisJMKtZog/I4YEtEJfQFH2+3zh0NeV0rZKGRnAAAA',
  },
  'cover-information-publicity': {
    src: '/images/portals/information-publicity-cover.webp',
    width: 1800,
    height: 1013,
    alt: {
      en: "A government press briefing in progress, with journalists seated before the departmental backdrop.",
      ta: "துறை பின்னணித் திரையின் முன் செய்தியாளர்கள் அமர்ந்திருக்க நடைபெறும் அரசு செய்தியாளர் சந்திப்பு.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMAAcABIByJbACdACRGPcNAAD8zAwBjRYxqPDr9ttkX40+Hgm90YorLprARPHyCFEkFxasPRUGmhqz12gUG13AAAA=',
  },
  'cover-egmore': {
    src: '/images/portals/egmore-cover.webp',
    width: 1800,
    height: 1013,
    alt: {
      en: "Walking a residential lane in the Egmore constituency, meeting residents at their doorsteps.",
      ta: "எழும்பூர் தொகுதியின் குடியிருப்புத் தெரு ஒன்றில் நடந்து, வீட்டு வாசல்களில் மக்களைச் சந்திக்கும் காட்சி.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoMAAcABIByJYwAAetMVQGQAPvPuwN0uUUQW+0UZqmM60UmjqZLq88GmWnFHoyPy8Aks8+4EfySVRJgAAA=',
  },
  'edu-classroom-students': {
    src: '/images/gallery/school-education/classroom-students.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Government school students gathered around a table with the minister during a classroom visit.",
      ta: "வகுப்பறை ஆய்வின்போது அமைச்சருடன் மேசையைச் சுற்றி அமர்ந்திருக்கும் அரசுப் பள்ளி மாணவர்கள்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAgABIByJZQCdADbggyrQAD+mxuqrIQe7Pb0PBivMr10tbxHGLGe5NsJv0IxEbRi2k76dBROAAAA',
  },
  'edu-primary-classroom': {
    src: '/images/gallery/school-education/primary-classroom.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "A primary classroom decorated with the alphabet, during a visit to a government school.",
      ta: "அரசுப் பள்ளி ஆய்வின்போது எழுத்துகளால் அலங்கரிக்கப்பட்ட ஒரு தொடக்கப் பள்ளி வகுப்பறை.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAgABIByJQBOgB6M2JaoiAD+BNd1Ta/YcMPIXcSZH9y1Jthb6VB4f8LE23YEnOPUGD5rTyKHB4i/gaAAAA==',
  },
  'edu-kit-distribution': {
    src: '/images/gallery/school-education/kit-distribution.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "School kits being handed to students at a School Education Department event.",
      ta: "பள்ளிக் கல்வித் துறை நிகழ்வில் மாணவர்களுக்கு வழங்கப்படும் பள்ளிப் பொருள் தொகுப்புகள்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABQAgCdASoMAAgABIByJYgC7H8AFjkgOAySJAAA/u3Wq40rXS5atKz4QsuIZPALebfioRUyMAY1hcL58SXU35muIlRshMaEibIWAAAA',
  },
  'edu-certificates': {
    src: '/images/gallery/school-education/certificates.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Students and teachers seated with certificates at a school ceremony.",
      ta: "பள்ளி விழா ஒன்றில் சான்றிதழ்களுடன் அமர்ந்திருக்கும் மாணவர்களும் ஆசிரியர்களும்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAAgABIByJZgAAxewa5AOAADh6ScFhUrU1sZ8+VsbXslMSuFr+DQUquRcSdQd7sxhwSAA',
  },
  'edu-infrastructure': {
    src: '/images/gallery/school-education/infrastructure.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Opening of a new school building block built under a school infrastructure programme.",
      ta: "பள்ளிக் கட்டமைப்புத் திட்டத்தின் கீழ் கட்டப்பட்ட புதிய பள்ளிக் கட்டிடத் தொகுதி திறப்பு.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAgABIByJZQAAmfhulR2AAD+lPxIUUXVKCKe66tsIL2cl0Xn6S5FV8bfYYSN56hd0Kh/hKXVCQGAOIAAAA==',
  },
  'edu-foundation-stone': {
    src: '/images/gallery/school-education/foundation-stone.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "A foundation stone being laid for a school construction project.",
      ta: "பள்ளிக் கட்டுமானப் பணிக்கான அடிக்கல் நாட்டு விழா.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAgABIByJZQCdAECotwJ5gAA9nUzEZ8cYPffTA1eQdYFfioXFPTQ1JSsgKe5jChQPhb9JOV6Jt6TK0AAAA==',
  },
  'edu-smart-classroom': {
    src: '/images/gallery/school-education/smart-classroom.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "A digital display in a government school classroom during a departmental visit.",
      ta: "துறை ஆய்வின்போது அரசுப் பள்ளி வகுப்பறையில் உள்ள மின்னணுத் திரைக் காட்சி.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAgABIByJYwC7AELVUhT5UAA/ut4RhQjfhocokA5c9jmGsJ6rTsLbHHAVTIelYQRCalaAmvtACKcm7SAAA==',
  },
  'edu-department-office': {
    src: '/images/gallery/school-education/department-office.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "At the School Education Department office, in front of the departmental nameboard.",
      ta: "பள்ளிக் கல்வித் துறை அலுவலகத்தில், துறையின் பெயர்ப் பலகையின் முன்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoMAAgABIByJbACdAELZV3DNxyAAP7nfSbVP31D+ewM4Wk8ek5ktZu4/r4GRcpGct3B2y+tOMp5nZY1AAA=',
  },
  'td-excavation-aerial': {
    src: '/images/gallery/tamil-development/excavation-aerial.webp',
    width: 1600,
    height: 1067,
    alt: {
      en: "Aerial view of an archaeological excavation, showing the exposed trenches and structures.",
      ta: "அகழாய்வுக் களத்தின் வான்வழிக் காட்சி — வெளிப்படுத்தப்பட்ட அகழிகளும் கட்டமைப்புகளும்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAAgABIByJQBOgB9ZGqyYAOJRJGFj9VbihTCyZaeKcjVfkfAnf1SMXmRBaz7AAAA=',
  },
  'td-excavation-site': {
    src: '/images/gallery/tamil-development/excavation-site.webp',
    width: 1600,
    height: 1067,
    alt: {
      en: "Visitors at an archaeological excavation site, walking the edge of the trenches.",
      ta: "அகழாய்வுக் களத்தில் அகழிகளின் ஓரமாக நடந்து செல்லும் பார்வையாளர்கள்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoMAAgABIByJYwCsAD7Fr8Eby4AAPntE8J03yTzDG+yAOZvOfyzaa42YczzScEeAAnKyOAA',
  },
  'td-rock-shelter': {
    src: '/images/gallery/tamil-development/rock-shelter.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Inspecting a rock shelter at a heritage site with departmental officials.",
      ta: "துறை அலுவலர்களுடன் பாரம்பரியக் களத்தில் ஒரு பாறை அடைவைப் பார்வையிடுதல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAgABIByJYwCdAEWTeP5CgAA/tUQKg1KuvJDKCpPNtGO0HjBX4MGFr3CiSbzrTO0p4tS2E0qFLF4bTHpUAAA',
  },
  'td-inscriptions': {
    src: '/images/gallery/tamil-development/inscriptions.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "A gallery of Tamil inscriptions on display, with explanatory panels.",
      ta: "விளக்கப் பலகைகளுடன் காட்சிக்கு வைக்கப்பட்டுள்ள தமிழ்க் கல்வெட்டுகளின் கூடம்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoMAAgABIByJbACdAD0rCyMaAD+hwQJbLFtdKW0frRTV+9Yi7W52thE/AXCw6UZ15FLiqm07KeqxFwAAAA=',
  },
  'td-museum-artefact': {
    src: '/images/gallery/tamil-development/museum-artefact.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Examining a carved artefact on display in a museum gallery.",
      ta: "அருங்காட்சியகக் கூடத்தில் காட்சிக்கு வைக்கப்பட்டுள்ள செதுக்கப்பட்ட தொல்பொருளை ஆய்தல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAAgABIByJbACdAELKYWzGAD+6DMWUe0ZnOvvGACRgOQMFAVodvrlk0P1HMXCMeJyZ88lAAA=',
  },
  'td-cultural-programme': {
    src: '/images/gallery/tamil-development/cultural-programme.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Performers in traditional dress at a cultural programme, photographed with officials.",
      ta: "பண்பாட்டு நிகழ்ச்சி ஒன்றில் பாரம்பரிய உடையணிந்த கலைஞர்கள், அலுவலர்களுடன்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAAgABIByJbACdAEQXsECMIAA/lsXkMrqaRC/Z5Zz3mnUYA+QhTuyFgDchmXn6A6Wxj52bNBtM4AA',
  },
  'td-awards': {
    src: '/images/gallery/tamil-development/awards.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "A certificate being presented at a Tamil Development Department function.",
      ta: "தமிழ் வளர்ச்சித் துறை நிகழ்வில் சான்றிதழ் வழங்கப்படும் காட்சி.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAAgABIByJYwCw7D0vBmcmhwA/sjyR7dEbRyc8Ce/Lg2uIv1YNoOfm5lenhp3mbvAvFCj3Cu8zspfAAA=',
  },
  'td-heritage-walk': {
    src: '/images/gallery/tamil-development/heritage-walk.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Officials walking a heritage site during a field inspection.",
      ta: "கள ஆய்வின்போது பாரம்பரியக் களத்தில் நடந்து செல்லும் அலுவலர்கள்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAgABIByJbACdACRo26AANucylCntlJHdcHexD4mPFuF99gcCeJM9Yn+YsX8/Ob5RgIQAAA=',
  },
  'dipr-press-microphones': {
    src: '/images/gallery/information-publicity/press-microphones.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Speaking to reporters at a bank of television news microphones.",
      ta: "தொலைக்காட்சி செய்தி ஒலிவாங்கிகளின் முன் செய்தியாளர்களிடம் பேசுதல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoMAAgABIByJQBdgMWR7Zic0y66oAD+xyOGiUg9AH1KtYgJZ2C7HMDhwD7pye2amZj5CD2kT4B1QaPbYKnP/ysDsatXmlCAAAA=',
  },
  'dipr-press-scrum': {
    src: '/images/gallery/information-publicity/press-scrum.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "A press interaction with reporters and camera crews gathered closely around.",
      ta: "செய்தியாளர்களும் ஒளிப்பதிவுக் குழுவினரும் சூழ்ந்திருக்க நடைபெறும் பத்திரிகைச் சந்திப்பு.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoMAAgABIByJZwAAlj95ZPgAP48ctP9aoohYEFj27vWu114xscjjfXuoXtkfMLmzx1yY/akEN0dPYOZgAA=',
  },
  'dipr-photo-archive': {
    src: '/images/gallery/information-publicity/photo-archive.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Viewing framed archival photographs displayed along a departmental corridor.",
      ta: "துறை நடைபாதையில் காட்சிப்படுத்தப்பட்டுள்ள சட்டமிட்ட ஆவணப் புகைப்படங்களைப் பார்வையிடுதல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMAAgABIByJQAAXWkykGdDkAD33CAZOVXq7j664JEX4H0sRLdc4bdaW9YalvKK3WUgD0xnxQAAAA==',
  },
  'dipr-archival-display': {
    src: '/images/gallery/information-publicity/archival-display.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "An archival photographic display being examined during a departmental visit.",
      ta: "துறை ஆய்வின்போது பார்வையிடப்படும் ஆவணப் புகைப்படக் காட்சி.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAgABIByJYwAAtxg8KOQAP62/Gu8yCvePAwMyT2fgWsJWco93EgODk6XwBuZWCFQW+M4AAA=',
  },
  'dipr-book-exhibition': {
    src: '/images/gallery/information-publicity/book-exhibition.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Books on display at a public exhibition stall.",
      ta: "பொதுக் கண்காட்சி அரங்கில் காட்சிக்கு வைக்கப்பட்டுள்ள நூல்கள்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoMAAgABIByJYgCdAEQdonScFYAAN5nNHJLz3m1W+oJP0cdsuXvOsfWRyFFFkpylJG2wA8Hei3NJr/GY8YCAAAA',
  },
  'dipr-book-stall': {
    src: '/images/gallery/information-publicity/book-stall.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Visiting a bookstall at a public event, with shelves of Tamil titles.",
      ta: "தமிழ் நூல்கள் அடுக்கப்பட்ட அலமாரிகளுடன், பொது நிகழ்வில் ஒரு நூல் அரங்கைப் பார்வையிடுதல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAgABIByJZAC7ADR9AY3AADiedv0Zy7qsvah7Yqx9JHZLdo376nPQyVlSDOvlMzK9uwzOk9fgAAA',
  },
  'dipr-press-conference': {
    src: '/images/gallery/information-publicity/press-conference.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "A seated press conference with officials behind a table of microphones.",
      ta: "ஒலிவாங்கிகள் நிறைந்த மேசையின் பின் அலுவலர்கள் அமர்ந்திருக்கும் செய்தியாளர் சந்திப்பு.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoMAAgABIByJQBdgBKQb4gAAPgzdcT1N99yjtrQ3TX9EySewUQKs5yId6PR1ujNQrWWEMqxrfzUcDl1OtgAAA==',
  },
  'dipr-media-gathering': {
    src: '/images/gallery/information-publicity/media-gathering.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Media crews assembled under a canopy ahead of an official announcement.",
      ta: "அலுவல்முறை அறிவிப்புக்கு முன் பந்தலின் கீழ் திரண்டிருக்கும் ஊடகக் குழுவினர்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoMAAgABIByJYwCdH8AFBLFbVdoAAD+oxQaiSd8DauLeUKVubzwJMFWr74vwjZnbMJ9amoQkSMynCgA',
  },
  'egmore-site-review': {
    src: '/images/gallery/egmore/site-review.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Reviewing plans with officials on a constituency street during a works inspection.",
      ta: "பணி ஆய்வின்போது தொகுதித் தெருவில் அலுவலர்களுடன் வரைபடங்களைப் பரிசீலித்தல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoMAAgABIByJYgAAlxmBI/+gAD7nKKe/H0gUxCXVbIdZ/coKTE8c0f5KJ8QYCdPTQw8I3s+2O9mSJf1v6TZdq+Y+ksGAAAA',
  },
  'egmore-public-facility': {
    src: '/images/gallery/egmore/public-facility.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Inside a newly built public sanitation facility in the constituency.",
      ta: "தொகுதியில் புதிதாகக் கட்டப்பட்ட பொதுக் கழிப்பிட வசதியின் உட்புறம்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAgABIByJaACdADcpZ4YPAAA/PsMJnZB5Eq+0kk/d5waGK50LW8ZRPJtL38RMRh4R8v9SfQZbbeI4fXN8lxgwPOAAA==',
  },
  'egmore-petitions': {
    src: '/images/gallery/egmore/petitions.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Receiving written petitions from residents during a constituency visit.",
      ta: "தொகுதி வருகையின்போது மக்களிடமிருந்து எழுத்துப்பூர்வ மனுக்களைப் பெறுதல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAgABIByJQBdgCHZC39xAADNm5K5hviDBjiV4hnvkI+tyKKkf5MaA2issYNeEbX57CVYF/tElMbpJUroAA==',
  },
  'egmore-doorstep': {
    src: '/images/gallery/egmore/doorstep.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Kneeling to speak with an elderly resident at the roadside.",
      ta: "சாலையோரத்தில் முதியவர் ஒருவருடன் மண்டியிட்டு உரையாடுதல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAAgABIByJZQC7AYstbS+AWAAzjVV5k7WL+OdSJREExPtuNCxTGfKvNp1J4ucBGPkINXE+3IuXkofAAA=',
  },
  'egmore-community-meal': {
    src: '/images/gallery/egmore/community-meal.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Serving food to residents at a community meal in the constituency.",
      ta: "தொகுதியில் நடைபெற்ற சமூக உணவு வழங்கல் நிகழ்வில் மக்களுக்கு உணவு பரிமாறுதல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAgABIByJYgCdAECpZDCeLgA/fzVymJXVdxLJN5o+M2+6rJbURG6p7Qzv6Jg9IOALLDG5EKAI7j3+xX1MAAA',
  },
  'egmore-inauguration': {
    src: '/images/gallery/egmore/inauguration.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Cutting the ribbon at the opening of a completed civic work.",
      ta: "நிறைவடைந்த பொதுப்பணி ஒன்றின் திறப்பு விழாவில் நாடா வெட்டுதல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoMAAgABIByJQBdgBuljYhHoAD+64sB1vfi6QiZsb4BJHYYglPQLBN1GEzb9mwYNfro82coGJnMK488SUgAAA==',
  },
  'egmore-street-meeting': {
    src: '/images/gallery/egmore/street-meeting.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "Meeting residents in a narrow residential lane in the constituency.",
      ta: "தொகுதியின் குறுகிய குடியிருப்புத் தெருவில் மக்களைச் சந்தித்தல்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoMAAgABIByJYwC7AEQXrsKrXgA/I++bx1d/oZHXTIVE9p6oBX7rCh3ZAr0GVPlzNhZ4EWEDOjsYKAAAAA=',
  },
  'egmore-public-gathering': {
    src: '/images/gallery/egmore/public-gathering.webp',
    width: 1400,
    height: 933,
    alt: {
      en: "A crowd of residents gathered during a walk through the constituency.",
      ta: "தொகுதி வலம் வரும்போது திரண்டிருக்கும் பொதுமக்கள்.",
    },
    blurDataURL: 'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoMAAgABIByJQBdgBuwks5aAADOORhr8ir8PxyggMuzk+R7kaGccuFAgT7HtUh8HcgF9aDwdzQ4ZXjUCHDI1hfssLgAAA==',
  },
};

/** Throws at build time if a page references an image that was never built. */
export function media(id: MediaId): ImageRef {
  const found = MEDIA[id];
  if (!found) throw new Error(`Missing media: ${id}. Run \`npm run images\`.`);
  return found;
}
