/**
 * Turn the project owner's raw photo library into the site's committed assets.
 *
 *   node scripts/build-images.mjs [--force]
 *
 * For each entry in image-manifest.mjs this writes:
 *   public/images/<to>                          the optimised WebP
 *   src/content/media/generated.ts              width, height, alt, blurDataURL
 *
 * The generated file is what pages import. Because it carries real intrinsic
 * dimensions, every <Image> reserves its exact box and the page never shifts as
 * photographs load — which matters more here than on most sites, since a
 * gallery grid of twelve 3:2 frames would otherwise reflow twelve times.
 *
 * `attention` cropping is used for the portrait hero so sharp centres the crop
 * on the subject rather than on the geometric middle of a 3:2 frame.
 */
import { mkdir, writeFile, access } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { IMAGES } from './image-manifest.mjs';

const SRC_ROOT = 'reference/Pictures';
const OUT_ROOT = 'public/images';
const GENERATED = 'src/content/media/generated.ts';
const QUALITY = 80;

const force = process.argv.includes('--force');

const exists = async (p) => {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
};

const records = [];
let built = 0;
let skipped = 0;
const missing = [];

for (const job of IMAGES) {
  const from = path.join(SRC_ROOT, job.from);
  const to = path.join(OUT_ROOT, job.to);

  if (!(await exists(from))) {
    missing.push(job.from);
    continue;
  }

  await mkdir(path.dirname(to), { recursive: true });

  if (force || !(await exists(to))) {
    let pipeline = sharp(from).rotate();

    if (job.aspect) {
      const [aw, ah] = job.aspect;
      pipeline = pipeline.resize({
        width: job.width,
        height: Math.round((job.width * ah) / aw),
        fit: 'cover',
        position: job.position === 'attention' ? sharp.strategy.attention : 'centre',
      });
    } else {
      pipeline = pipeline.resize({ width: job.width, fit: 'inside', withoutEnlargement: true });
    }

    await pipeline.webp({ quality: QUALITY, effort: 5 }).toFile(to);
    built += 1;
  } else {
    skipped += 1;
  }

  const meta = await sharp(to).metadata();

  // A 12px-wide WebP is ~120 bytes as a data URI — small enough to inline for
  // every image on the page without measurably affecting the HTML size.
  const blur = await sharp(to).resize(12).webp({ quality: 25 }).toBuffer();

  records.push({
    id: job.id,
    src: `/images/${job.to.split(path.sep).join('/')}`,
    width: meta.width,
    height: meta.height,
    alt: job.alt,
    blurDataURL: `data:image/webp;base64,${blur.toString('base64')}`,
  });
}

const header = `// GENERATED by scripts/build-images.mjs — do not edit by hand.
// Run \`npm run images\` after changing scripts/image-manifest.mjs.
import type { ImageRef } from '@/lib/content/schema';

export type MediaId = ${records.map((r) => `'${r.id}'`).join(' | ') || 'never'};

export const MEDIA: Readonly<Record<MediaId, ImageRef>> = {
`;

const body = records
  .map(
    (r) => `  '${r.id}': {
    src: '${r.src}',
    width: ${r.width},
    height: ${r.height},
    alt: {
      en: ${JSON.stringify(r.alt.en)},
      ta: ${JSON.stringify(r.alt.ta)},
    },
    blurDataURL: '${r.blurDataURL}',
  },`,
  )
  .join('\n');

const footer = `
};

/** Throws at build time if a page references an image that was never built. */
export function media(id: MediaId): ImageRef {
  const found = MEDIA[id];
  if (!found) throw new Error(\`Missing media: \${id}. Run \\\`npm run images\\\`.\`);
  return found;
}
`;

await mkdir(path.dirname(GENERATED), { recursive: true });
await writeFile(GENERATED, header + body + footer, 'utf8');

console.log(`built ${built}, reused ${skipped}, total ${records.length}`);
console.log(`wrote ${GENERATED}`);

if (missing.length > 0) {
  console.warn(`\n${missing.length} source file(s) not found under ${SRC_ROOT}/:`);
  for (const name of missing) console.warn(`  - ${name}`);
  console.warn('These are absent from the generated manifest; pages referencing them will fail to build.');
}
